"""empty message

Revision ID: 5c694bf1a388
Revises: 56fc9a1898f6
Create Date: 2018-11-15 23:51:50.038700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c694bf1a388'
down_revision = '56fc9a1898f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_buku', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id'], ),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_cart')
    # ### end Alembic commands ###
