"""empty message

Revision ID: 9fe6201f8904
Revises: 
Create Date: 2018-11-05 19:22:21.912119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe6201f8904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('no_telp', sa.String(length=255), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('penerbit', sa.String(length=255), nullable=True),
    sa.Column('kategori', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('url_picture', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('pelapak_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategori'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['pelapak_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buku')
    op.drop_table('users')
    op.drop_table('kategori')
    # ### end Alembic commands ###
